config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :articles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true
  validates :description, presence: true
  validates :category, presence: true
  has_one_attached :image

  def self.search(search)
    where("description ILIKE ? OR title ILIKE ?", "%#{search}%","%#{search}%")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
     flash[:notice] = "Article was successfully created"
     redirect_to article_path(@article)
    else
     render 'new'
    end
  end

  def show
  end

  def update
    if @article.update(article_params)
     flash[:notice] = "Article was updated"
     redirect_to article_path(@article)
    else
     flash[:notice] = "Article was not updated"
     render 'edit'
    end
  end

  def edit
  end

  def index
    @articles = Article.all
    if params[:search]
      @articles = Article.search(params[:search]).order("created_at DESC")
    else
      @articles = Article.all.order("created_at DESC")
    end
  end

  def destroy
    @article.destroy
    flash[:notice] = "Article was deleted"
    redirect_to articles_path
  end

  private

    def article_params
     params.require(:article).permit(:title, :category, :description, :description1, :description2, :description3, :description4, :description5, :description6, :description7, :description8, :image)
    end

  def set_article
     @article = Article.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @articles = Article.all
    if params[:search]
      @articles = Article.search(params[:search]).order("created_at DESC")
    else
      @articles = Article.all.order("created_at DESC")
    end
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/create.html.erb
<h1>Articles#create</h1>
<p>Find me in app/views/articles/create.html.erb</p>

app/views/articles/destroy.html.erb
<h1>Articles#destroy</h1>
<p>Find me in app/views/articles/destroy.html.erb</p>

app/views/articles/edit.html.erb
<div class="light-red-background">

  <div class="container">

    <h1>Add a blog entry</h1>
    <%= simple_form_for @article do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :description1 %>
    <%= f.input :description2 %>
    <%= f.input :description3 %>
    <%= f.input :description4 %>
    <%= f.input :description5 %>
    <%= f.input :description6 %>
    <%= f.input :description7 %>
    <%= f.input :description8 %>
    <%= f.input :category %>
    <%= f.input :image, as: :file %>
    <%= f.button :submit, class: "btn-primary" %>
    <%= f.button :button, "Cancel", type: "reset", class: "btn-outline-secondary" %>
    <% end %>
  </div>
</div>

app/views/articles/index.html.erb
<div class="padding-top-20 light-red-background">
  <div class="container">
    <div class="cards">
      <% @articles.each do |article| %>
        <div class="each-card">
          <%= link_to article_path(article) do %>
            <%= cl_image_tag(article.image.key, class:"card-category center-image") %>
            <p class="card-date"><%= article.created_at.strftime("%d.%m.%y") %></p>
            <h2 class="card-head"><%= article.title %></h2>
            <p class="card-text limit-text"><%= article.description %></p>
          <% end %>
        </div>
      <% end %>
    </div>
    <% link_to 'new', new_article_path %>
  </div>
</div>

app/views/articles/new.html.erb
<div class="light-red-background">

  <div class="container">

    <h1>Add a blog entry</h1>
    <%= simple_form_for @article do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :description1 %>
    <%= f.input :description2 %>
    <%= f.input :description3 %>
    <%= f.input :description4 %>
    <%= f.input :description5 %>
    <%= f.input :description6 %>
    <%= f.input :description7 %>
    <%= f.input :description8 %>
    <%= f.input :category %>
    <%= f.input :image, as: :file %>
    <%= f.button :submit, class: "btn-primary" %>
    <%= f.button :button, "Cancel", type: "reset", class: "btn-outline-secondary" %>
    <% end %>
  </div>
</div>

app/views/articles/show.html.erb
<div class="light-red-background">

  <div class="container">
    <h1 class="text-center" style="margin-top: 24px; font-size:28px;"><%= @article.title %></h1>
    <p class="text-center" style="font-size:12px; opacity: 70%;"><%= @article.created_at.strftime("%b %d, %Y") %></p>
      <%= cl_image_tag(@article.image.key, class:"show-image center") %>
      <div class="show-text">
        <p style="text-align: justify; margin-top: 20px;"><%= @article.description %></p>
        <p style="text-align: justify;"><%= @article.description1 %></p>
        <p style="text-align: justify;"><%= @article.description2 %></p>
        <p style="text-align: justify;"><%= @article.description3 %></p>
        <p style="text-align: justify;"><%= @article.description4 %></p>
        <p style="text-align: justify;"><%= @article.description5 %></p>
        <p style="text-align: justify;"><%= @article.description6 %></p>
        <p style="text-align: justify;"><%= @article.description7 %></p>
        <p style="text-align: justify;"><%= @article.description8 %></p>
        <p>X Luca</p>
        <%= link_to 'Delete', article_path(@article), method: :delete, data: {confirm: "Are you sure?"} %>

      </div>
  </div>
</div>

app/views/layouts/_banner.html.erb
<div id="word-placement"></div>
<h1 class="banner-header text-center red-background" style="font-size: 72px;" id="">Luca's Blog</h1>
<h1 class="banner-header red-background" id=""></h1>

<div id="wave"></div>

  <nav class="navbar navbar-expand-lg navbar-light white-nav">
    <!-- <a class="navbar-brand" href="#">Navbar</a> -->
    <button class="navbar-toggler " type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse d-flex justify-content-around" id="navbarNavDropdown">
      <ul class="navbar-nav">

        <li class="nav-item <%= 'active' if current_page?(about_path) %>">
          <%= link_to about_path do %>about
            <%= (content_tag :span, "(current)", class:"sr-only nav-link" ) if current_page?(about_path) %>
          <% end %>
        </li>

        <li class="nav-item <%= 'active' if current_page?(articles_path) %>">
          <%= link_to articles_path do %>blog
            <%= (content_tag :span, "(current)", class:"sr-only nav-link" ) if current_page?(articles_path) %>
          <% end %>
        </li>
        <li class="nav-item <%= 'active' if current_page?(contact_path) %>">
          <%= link_to contact_path do %>contact
            <%= (content_tag :span, "(current)", class:"sr-only nav-link" ) if current_page?(contact_path) %>
          <% end %>
        </li>



        <!-- <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown link
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li> -->
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/_footer.html.erb
<div id="wave2"></div>
<div class="red-box d-flex align-items-end justify-content-center">
  <ul>
    <li>
      <a href="https://www.instagram.com/lucakuhn/"><i class="fab fa-instagram"></i></a>
    </li>
    <li>
      <a href="https://www.linkedin.com/in/luca-kuhn-bbb779ab/"><i class="fab fa-linkedin-in"></i></a>
    </li>
  </ul>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-light bg-light justify-content-between red-background">
  <%= link_to "lnb", root_path, class: "navbar-brand", id: "logo" %>
  <div class="search form-inline">
    <%= form_tag(articles_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search", class: "form-control form-control2" %>
    <% end %>
  </div>
</nav>




 <!--  <div class="my-links">
    <i class="fab fa-linkedin"></i>
    <i class="fab fa-instagram-square"></i>
  </div> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NutritionBlog1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <!-- <base target="_blank"> -->
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/banner' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <div class="show-text" style="height:200px;">
    <h1 class="text-center" style="margin-top: 32px; font-size: 20px;">About Luca</h1>
    <p></p>
  </div>
  <% link_to 'Home', root_path %>
</div>

app/views/pages/contact.html.erb
<div class="container">
  <p class="text-center" style="height: 200px; margin-top: 100px;">E-mail: luca.francesca.kuhn@gmail.com</p>
</div>

app/views/pages/index.html.erb
<div class="padding-top-20 light-red-background">
  <div class="container">
    <div class="cards">
      <% @articles.each do |article| %>
        <div class="each-card">
          <%= link_to article_path(article) do %>
            <%= cl_image_tag(article.image.key, class:"card-category center-image") %>
            <p class="card-date"><%= article.created_at.strftime("%d.%m.%y") %></p>
            <h2 class="card-head"><%= article.title %></h2>
            <p class="card-text limit-text"><%= article.description %></p>
          <% end %>
        </div>
      <% end %>
    </div>
    <% link_to 'new', new_article_path %>
  </div>
</div>